[mypy]
python_version = 3.12
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-novestia.*]
disallow_untyped_defs = True

[mypy-opentelemetry.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True
